CREATE DATABASE QuanLyNhanVien_Nhom1bannhap2;
GO
USE QuanLyNhanVien_Nhom1bannhap2;
GO
CREATE TABLE tblPhongBan (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MaPB VARCHAR(10) UNIQUE NOT NULL,
    TenPB NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(200),
    SoDienThoai VARCHAR(20),
    GhiChu NVARCHAR(255),
    DeletedAt INT NOT NULL DEFAULT 0
);
GO
CREATE TABLE tblChucVu (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MaCV VARCHAR(10) UNIQUE NOT NULL,
    TenCV NVARCHAR(100) NOT NULL,
    GhiChu NVARCHAR(255),
    DeletedAt INT NOT NULL DEFAULT 0,
    MaPB VARCHAR(10) NOT NULL,
    CONSTRAINT FK_ChucVu_PhongBan
        FOREIGN KEY (MaPB) REFERENCES tblPhongBan(MaPB)
);
GO
CREATE TABLE tblNhanVien (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MaNV VARCHAR(10) UNIQUE NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE,
    GioiTinh NVARCHAR(10),
    DiaChi NVARCHAR(200),
    SoDienThoai VARCHAR(20),
    Email VARCHAR(100),
    MaCV VARCHAR(10) NOT NULL,
    GhiChu NVARCHAR(255),
    DeletedAt INT NOT NULL DEFAULT 0,
    CONSTRAINT FK_NhanVien_ChucVu
        FOREIGN KEY (MaCV) REFERENCES tblChucVu(MaCV)
);
GO
	CREATE TABLE tblHopDong (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MaHopDong VARCHAR(10) UNIQUE NOT NULL,
    MaNV VARCHAR(10) NOT NULL,
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE,
    LoaiHopDong NVARCHAR(50),
    LuongCoBan DECIMAL(18,2) NOT NULL,
    GhiChu NVARCHAR(255),
    DeletedAt INT NOT NULL DEFAULT 0,
    CONSTRAINT FK_HopDong_NhanVien
        FOREIGN KEY (MaNV) REFERENCES tblNhanVien(MaNV)
);
GO
CREATE TABLE tblChamCong (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MaChamCong VARCHAR(20) UNIQUE NOT NULL,
    MaNV VARCHAR(10) NOT NULL,
    Ngay DATE NOT NULL,
    GioVao TIME NOT NULL,
    GioVe TIME NOT NULL,
    GhiChu NVARCHAR(255),
    DeletedAt INT NOT NULL DEFAULT 0,
    CONSTRAINT FK_ChamCong_NhanVien
        FOREIGN KEY (MaNV) REFERENCES tblNhanVien(MaNV)
);
GO
CREATE TABLE tblLuong (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MaLuong VARCHAR(10) UNIQUE NOT NULL,
    Thang INT CHECK (Thang BETWEEN 1 AND 12),
    Nam INT NOT NULL,
    LuongCoBan DECIMAL(18,2) NOT NULL,
    SoNgayCongChuan INT DEFAULT 26,
    PhuCap DECIMAL(18,2) DEFAULT 0,
    KhauTru DECIMAL(18,2) DEFAULT 0,
    GhiChu NVARCHAR(255),
    DeletedAt INT NOT NULL DEFAULT 0,
    ChamCongId INT NOT NULL,
    CONSTRAINT FK_Luong_ChamCong
        FOREIGN KEY (ChamCongId) REFERENCES tblChamCong(Id)
);
GO
CREATE TABLE tblDuAn (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MaDA VARCHAR(10) UNIQUE NOT NULL,
    TenDA NVARCHAR(200) NOT NULL,
    MoTa NVARCHAR(500),
    NgayBatDau DATE,
    NgayKetThuc DATE,
    GhiChu NVARCHAR(255),
    DeletedAt INT NOT NULL DEFAULT 0
);
GO
CREATE TABLE tblChiTietDuAn (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MaNV VARCHAR(10) NOT NULL,
    MaDA VARCHAR(10) NOT NULL,
    VaiTro NVARCHAR(100),
    GhiChu NVARCHAR(255),
    DeletedAt INT NOT NULL DEFAULT 0,

    CONSTRAINT UQ_ChiTietDuAn UNIQUE (MaNV, MaDA),

    CONSTRAINT FK_ChiTietDuAn_NhanVien
        FOREIGN KEY (MaNV) REFERENCES tblNhanVien(MaNV),

    CONSTRAINT FK_ChiTietDuAn_DuAn
        FOREIGN KEY (MaDA) REFERENCES tblDuAn(MaDA)
);
GO
CREATE TABLE tblRole (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    TenRole NVARCHAR(50) UNIQUE NOT NULL,
    MoTa NVARCHAR(200)
);
GO
CREATE TABLE tblTaiKhoan (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MaTK VARCHAR(10) UNIQUE NOT NULL,
    MaNV VARCHAR(10) UNIQUE NOT NULL,
    SoDienThoai VARCHAR(50) UNIQUE NOT NULL,
    MatKhau VARCHAR(255) NOT NULL,
    Quyen NVARCHAR(50),
    GhiChu NVARCHAR(255),
    DeletedAt INT NOT NULL DEFAULT 0,
    RoleId INT,
    CONSTRAINT FK_TaiKhoan_NhanVien
        FOREIGN KEY (MaNV) REFERENCES tblNhanVien(MaNV),
    CONSTRAINT FK_TaiKhoan_Role
        FOREIGN KEY (RoleId) REFERENCES tblRole(Id)
);
GO
